{
	"version": 1733443965,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/Игрок-sheet0.png",
		"images/Игрок-sheet1.png",
		"images/ТрупПосле-sheet0.png",
		"images/Трава.png",
		"images/Пуля-sheet0.png",
		"images/Пуля-sheet1.png",
		"images/particles.png",
		"images/ПанелькаИгрока-sheet0.png",
		"images/Стены-sheet0.png",
		"images/Стены-sheet1.png",
		"images/Пол.png",
		"images/Тропы-sheet0.png",
		"images/Тропы-sheet1.png",
		"images/Партиклразрушения-sheet0.png",
		"images/Партиклразрушения-sheet1.png",
		"images/Партиклразрушения-sheet2.png",
		"images/vrag-sheet0.png",
		"images/улицанормальная-sheet0.png",
		"images/улицанормальная-sheet1.png",
		"images/penisi-sheet0.png",
		"images/ДжойстикБаза-sheet0.png",
		"images/Джойстик-sheet0.png",
		"images/взрыв.png",
		"images/взрывпыль.png",
		"images/sprite-sheet0.png",
		"images/bakudan-sheet0.png",
		"images/zombutrigger-sheet0.png",
		"images/stando-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/сетоваляпыльЧАКРА3.png",
		"images/step.png",
		"images/sprite5-sheet0.png",
		"images/localgame-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/spawnpoint-sheet0.png",
		"media/crazy diamond barrage.ogg",
		"media/gold experience barrage.ogg",
		"media/king crimson barrage.ogg",
		"media/star platinum barrage.ogg",
		"media/star platinum the world over heaven act 4 love train bites the dust moon requiem barrage.ogg",
		"media/the world barrage.ogg",
		"media/time earase.ogg",
		"media/time stop.ogg",
		"media/btd.ogg",
		"media/requiem.ogg",
		"media/bakudanchik.ogg",
		"media/killer-queen-summon.ogg",
		"media/bakudanboom.ogg",
		"media/unsum.ogg",
		"media/sum.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"not the joseph toster.pdn",
		"Photon-Javascript_SDK.min.js",
		"pathfind.js"
	]
}